"""Lectura ususarios

Revision ID: 229f99b3614b
Revises: 0dbe770da2d4
Create Date: 2025-05-31 17:17:52.626974

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '229f99b3614b'
down_revision = '0dbe770da2d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observation', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=800),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_view_all_puestos', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('can_view_all_puestos')

    with op.batch_alter_table('observation', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.String(length=800),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###
