"""Eliminar columna zona de User

Revision ID: c33ea248df15
Revises: 5a85d36218f8
Create Date: 2025-05-19 10:22:26.597949

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c33ea248df15'
down_revision = '5a85d36218f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('zona')

    with op.batch_alter_table('user_puesto_assignment', schema=None) as batch_op:
        batch_op.alter_column('puesto',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_puesto_assignment', schema=None) as batch_op:
        batch_op.alter_column('puesto',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zona', mysql.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
